// Code generated by "stringer -type Role -trimprefix Role"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleFollower-0]
	_ = x[RoleCandidate-1]
	_ = x[RoleLeader-2]
}

const _Role_name = "FollowerCandidateLeader"

var _Role_index = [...]uint8{0, 8, 17, 23}

func (i Role) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Role_index)-1 {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[idx]:_Role_index[idx+1]]
}
